# Generated by Django 5.1.5 on 2025-01-18 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_id_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('martial_status', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_phone_number', models.CharField(max_length=15)),
                ('alternate_email', models.EmailField(max_length=255)),
                ('pan_number', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('PA_address', models.CharField(max_length=255)),
                ('PA_pincode', models.CharField(max_length=6)),
                ('PA_state', models.CharField(max_length=50)),
                ('PA_city', models.CharField(max_length=50)),
                ('CA_address', models.CharField(max_length=255)),
                ('CA_pincode', models.CharField(max_length=6)),
                ('CA_state', models.CharField(max_length=50)),
                ('CA_city', models.CharField(max_length=50)),
                ('type_of_employment', models.CharField(max_length=50)),
                ('employer_type', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('EA_address', models.CharField(max_length=255)),
                ('EA_pincode', models.CharField(max_length=6)),
                ('EA_state', models.CharField(max_length=50)),
                ('EA_city', models.CharField(max_length=50)),
                ('official_mail_id', models.EmailField(max_length=255)),
                ('work_experience', models.CharField(max_length=50)),
                ('monthly_income', models.IntegerField()),
                ('existing_emis', models.IntegerField()),
                ('annual_income', models.IntegerField()),
                ('annual_profit', models.IntegerField()),
                ('loan_product', models.CharField(max_length=50)),
                ('loan_amount', models.IntegerField()),
                ('loan_tenure', models.IntegerField()),
                ('property_identification', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('developer_name', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('typology', models.CharField(max_length=50)),
                ('stage_of_construction', models.CharField(max_length=50)),
                ('property_value', models.IntegerField()),
                ('property_address', models.CharField(max_length=255)),
                ('property_pincode', models.CharField(max_length=6)),
                ('property_state', models.CharField(max_length=50)),
                ('property_city', models.CharField(max_length=50)),
                ('name_of_closing_agent', models.CharField(max_length=255)),
                ('loan_status', models.CharField(choices=[('IN-PROGRESS', 'In Progress'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], max_length=50)),
                ('disbursement_date', models.DateField()),
                ('disbursed_amount', models.IntegerField()),
                ('loan_emis', models.IntegerField()),
                ('loan_interest_rate', models.IntegerField()),
                ('loan_processing_fee', models.IntegerField()),
                ('loan_sanctioned_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications_creation', to='users.user')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications_modification', to='users.user')),
            ],
            options={
                'db_table': 'loan_applications',
                'managed': (False,),
            },
        ),
    ]
