# Generated by Django 5.1.5 on 2025-01-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_loanapplication_disbursement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_sanctioned_date',
            field=models.DateField(null=True),
        ),
    ]
