# Generated by Django 5.1.5 on 2025-01-18 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_loanapplication_loan_sanctioned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications_modification', to='users.user'),
        ),
    ]
