# Generated by Django 5.1.5 on 2025-01-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_loanapplication_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='aadhar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='itr',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='salary_slips',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
