# Generated by Django 5.1.5 on 2025-01-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_loanapplication_aadhar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('company_address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_project_creation', to='users.user')),
            ],
            options={
                'db_table': 'corporate_project_details',
            },
        ),
    ]
