# Generated by Django 5.1.5 on 2025-02-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_corporateprojectdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
