# Generated by Django 5.1.5 on 2025-02-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_loanapplication_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='property_value',
            field=models.IntegerField(null=True),
        ),
    ]
