# Generated by Django 5.1.5 on 2025-02-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_loanapplication_property_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='annual_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='annual_profit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='disbursed_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='existing_emis',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_emis',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_interest_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_processing_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_tenure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='official_mail_id',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='property_identification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='work_experience',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
